In [1]:
import os
import pandas as pd

In [27]:
# os.listdir('.\pages')
files = os.listdir('..\pages')
files.sort()
files

['01 Home_max_slidebar.py',
 '02 Category.py',
 '03 Genre.py',
 '04 DLC_Counts.py',
 '05 Price.py',
 '06 Age_Restriction.py',
 '07 Settings.py',
 '08 OS.py',
 '09 Developer.py',
 '10 Publisher.py',
 '11 ForcaSteam.py',
 '12 Tensorflow.py',
 '13 switch_page_text.py']

In [20]:
names = []
for name in files:
    name = name.split()[1].replace('.py', '').replace('_', ' ')
    names.append(name)
    
names

['Home max slidebar',
 'Publisher',
 'ForcaSteam',
 'Tensorflow',
 'switch page text',
 'Category',
 'Genre',
 'DLC Counts',
 'Price',
 'Age Restriction',
 'Settings',
 'OS',
 'Developer']

In [24]:
import sys
os.path.basename(sys.argv[0])

'ipykernel_launcher.py'

In [2]:
df = pd.read_csv('../data/join_02.csv')
df.head()

,gamename,year,month,avg,gain,peak,avg_peak_perc,date,release_date,required_age,...,genre_sports,genre_racing,genre_rpg,genre_simulation,indie,full_audio,full_controller_support,age_0_plus,age_13_plus,age_18_plus
0,100% Orange Juice,2021,February,278.67,-25.23,645,43.2047%,2021-02-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
1,100% Orange Juice,2021,January,303.89,-4.16,614,49.4935%,2021-01-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
2,100% Orange Juice,2020,December,308.05,23.02,743,41.4603%,2020-12-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
3,100% Orange Juice,2020,November,285.03,-7.41,621,45.8986%,2020-11-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
4,100% Orange Juice,2020,October,292.45,46.68,900,32.4944%,2020-10-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0

In [3]:
# Format preparation
df['date'] = pd.to_datetime(df['date'])
df['release_date'] = pd.to_datetime(df['release_date'])
df['avg_peak_perc'] = df['avg_peak_perc'].str.rstrip('%').astype('float') 
df = df.dropna()

In [16]:
gamenames = df['gamename'].unique()

def search(target):
    result = []
    for gamename in gamenames:
        if target.lower() in gamename.lower():
            result.append(gamename)
    return result 

favorite_game = search("orange")[0]
favorite_game

'100% Orange Juice'

In [20]:
df

,gamename,year,month,avg,gain,peak,avg_peak_perc,date,release_date,required_age,...,genre_sports,genre_racing,genre_rpg,genre_simulation,indie,full_audio,full_controller_support,age_0_plus,age_13_plus,age_18_plus
0,100% Orange Juice,2021,February,278.67,-25.23,645,43.2047,2021-02-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
1,100% Orange Juice,2021,January,303.89,-4.16,614,49.4935,2021-01-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
2,100% Orange Juice,2020,December,308.05,23.02,743,41.4603,2020-12-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
3,100% Orange Juice,2020,November,285.03,-7.41,621,45.8986,2020-11-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
4,100% Orange Juice,2020,October,292.45,46.68,900,32.4944,2020-10-01,2014-05-16,0,...,0,0,0,0,1,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63848,theHunter Classic,2014,November,844.43,-65.03,1683,50.1741,2014-11-01,2014-06-03,0,...,1,0,0,1,0,1,0,1,0,0
63849,theHunter Classic,2014,October,909.46,258.77,2293,39.6625,2014-10-01,2014-06-03,0,...,1,0,0,1,0,1,0,1,0,0
63850,theHunter Classic,2014,September,650.69,-63.60,1717,37.8969,2014-09-01,2014-06-03,0,...,1,0,0,1,0,1,0,1,0,0
63851,theHunter Classic,2014,August,714.29,-337.67,1181,60.4818,2014-08-01,2014-06-03,0,...,1,0,0,1,0,1,0,1,0,0
63852,theHunter Classic,2014,July,1051.96,-110.53,2059,51.0908,2014-07-01,2014-06-03,0,...,1,0,0,1,0,1,0,1,0,0

In [21]:
df_filter = df[df['gamename']!=favorite_game]
df_filter.head()

,gamename,year,month,avg,gain,peak,avg_peak_perc,date,release_date,required_age,...,genre_sports,genre_racing,genre_rpg,genre_simulation,indie,full_audio,full_controller_support,age_0_plus,age_13_plus,age_18_plus
84,12 is Better Than 6,2021,February,5.24,-0.70,13,40.3077,2021-02-01,2015-11-20,0,...,0,0,0,0,1,0,1,1,0,0
85,12 is Better Than 6,2021,January,5.94,0.78,18,33.0000,2021-01-01,2015-11-20,0,...,0,0,0,0,1,0,1,1,0,0
86,12 is Better Than 6,2020,December,5.16,-0.08,21,24.5714,2020-12-01,2015-11-20,0,...,0,0,0,0,1,0,1,1,0,0
87,12 is Better Than 6,2020,November,5.24,0.89,18,29.1111,2020-11-01,2015-11-20,0,...,0,0,0,0,1,0,1,1,0,0
88,12 is Better Than 6,2020,October,4.35,0.64,38,11.4474,2020-10-01,2015-11-20,0,...,0,0,0,0,1,0,1,1,0,0

In [35]:
import numpy

In [37]:
top_games = df.gamename.unique()[0:5]
# top_games.append(favorite_game)
top_games = numpy.append(top_games, favorite_game)
top_games

array(['100% Orange Juice', '12 is Better Than 6', '140', '60 Seconds!',
       '7 Days to Die', '100% Orange Juice'], dtype=object)